version: "3.9"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
      - APP_POOL=blue
    ports:
      - "8081:${PORT}"
    restart: always

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
      - APP_POOL=green
    ports:
      - "8082:${PORT}"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"          # Expose Nginx entry point
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # Mount your config
    restart: always

