version: "3.9"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
      - APP_POOL=blue
    ports:
      - "8081:${PORT}"
    restart: always

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
      - APP_POOL=green
    ports:
      - "8082:${PORT}"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/start.sh:/start.sh:ro
    command: ["/start.sh"]
    restart: always
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}

  alert_watcher:
    build:
      context: .
      dockerfile: watcher.Dockerfile
    container_name: alert_watcher
    depends_on:
      - nginx
    volumes:
      - ./nginx/logs:/var/log/nginx:ro
    env_file:
      - .env
    restart: always

